### ISSUE TITLE
Merged it into LG version 5.2.1

### ISSUE THREAD

**Issue by linas** [lumenrobot/link-grammar-id#1]
Hi Hendy,

I recently found this, and merged it into LG version 5.2.1, so that it comes with the default install.

**Comment by ceefour** [comment]
Thank you @linas but I'm confused... this project is incomplete and is not ready to be published.

**Comment by linas** [comment]
Think of it as advertising.  FWIW, the English dicts are also incomplete.  They will never actually be complete..

**Comment by linas** [comment]
advertising: viz, the more people know about it, the more likely they will come and help.

**Comment by ceefour** [comment]
Thanks @linas... I understand now. :)
